### ISSUE TITLE
Way to document data catalogue in code

### ISSUE THREAD

**Issue by byapparov** [byapparov/usegs#1]
```r
library(httr)
url.base <- "https://raw.githubusercontent.com/{organisation}/{repository}/master/"
schema.path <- "purchase-order/schema/purchase-order.json"
url <- paste0(url.base, schema.path)
x <- GET(url, authenticate(Sys.getenv("GITHUB_PAT"), ""))
response <- content(x, as="text", type = "text", encoding = "UTF-8")
schema.table <- fromJSON(response)
```

```yaml
# .catalogue

- purchase-order
  - file: schema/purchase-order.json
- sale-order-line
  - file: ...
```
